### ISSUE TITLE
Issue with explain-method

### ISSUE THREAD

**Issue by i3mainzroussel** [Ziqi-Li/geoshapley#5]
Hi @Ziqi-Li ,

I wanted to try your package after I read your interesting paper. I'm having difficulties using the .explain method.
When I use the following code, I get the error 

```
background = X_train.sample(10).values
mlp_explainer = GeoShapleyExplainer(clf.predict, background)
mlp_rslt = mlp_explainer.explain(background)
```
`"AttributeError: 'numpy.ndarray' object has no attribute 'values'" for the last line."`

If I remove the .values in line 1, I get another exception:
```
background = X_train.sample(10)
mlp_explainer = GeoShapleyExplainer(clf.predict, background)
mlp_rslt = mlp_explainer.explain(background)
```
` "InvalidIndexError: (0, slice(None, None, None))"`

Could you help me out what my problem might be?
My X_train contains features and coordinate pairs (last two columns). I use XGB for a classification problem. Does your package work for classifications or was it developed for regression tasks?

Many thanks!

**Comment by Ziqi-Li** [comment]
Hi @i3mainzroussel,

There might be a couple of reasons, but one thing I noticed is your `mlp_rslt = mlp_explainer.explain(background)` is trying to explain the background data. Usually we explain the entire data or your training data. Essentially, if you do:

```
background = X_train.sample(10).values
mlp_explainer = GeoShapleyExplainer(clf.predict, background)
mlp_rslt = mlp_explainer.explain(X_train)
```
Then this should work. I will improve the documentation a bit later.

Regarding classification, yes, it supports classification. Usually for a classifier, it will have two prediction functions one is `.predict()` the other is `predict_proba()`. `.predict()` returns the binary result while `predict_proba()` will give you the probabilities of each class. So if you want to use `predict_proba()` then you need to write a function wrapper to make sure it will give an output with size n by 1 then you can put it into the `.explain()` function. 

Please let me know if you have further questions.

**Comment by i3mainzroussel** [comment]
Hi @Ziqi-Li 

thanks for looking into it. I changed to explain X_train.
Unfortunately, this leads to the problem, that the method wants to generate a way too big array, shape (8589934592, 66) in my case. X_train has the size [3829 rows x 34 columns]. But this would be more a problem on my side I think.
Thanks for helping.
