### ISSUE TITLE
"explain" fuction error with XGBoost model

### ISSUE THREAD

**Issue by xuzzhan** [Ziqi-Li/geoshapley#8]
i use "xgb.train" func to train a model, and generate xgb explainer with GeoShapleyExplainer. But there will be error reported if i use "explain" function. Like follows:
`from geoshapley import GeoShapleyExplainer`
`xgb_model = xgb.train(...)`
`background_X = X.values`
`xgb_explainer = GeoShapleyExplainer(xgb_model.predict, background_X)`
`xgb_rslt = xgb_explainer.explain(X, n_jobs=-1)`

TypeError: ('Expecting data to be a DMatrix object, got: ', <class 'numpy.ndarray'>)

So perhaps X_geo needs to be corrected in explain function, i guess. Tks!

**Comment by Ziqi-Li** [comment]
Sorry for the delayed reply. The reason for the error is that your prediction function `xgb_model.predict` needs to take `DMatrix` as how the model (based on your API) was trained, but the `background_X` is an numpy array. If you make them consistent to be numpy array, the explain function should work.
